"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from datetime import timedelta
from settings import *

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "ASDF"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition
INSTALLED_APPS += ['debug_toolbar']

MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware']

EMAIL_HOST_USER = 'mitbattlecode@gmail.com'
EMAIL_HOST_PASSWORD = '6v&wG72nvU*x'
SENDGRID_API_KEY = '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'


"""
# log all SQL queries to console
LOGGING = {
    'version': 1,
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        }
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
        }
    },
    'loggers': {
        'django.db.backends': {
            'level': 'DEBUG',
            'handlers': ['console'],
        }
    }
}
"""



# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

# the test database
# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql_psycopg2',
#        'NAME': 'battlecode',
#        'USER': 'battlecode',
#        'PASSWORD': '1f8e8ea0b0e34e279a6e71225da3419f1a4aef62',
#        'HOST': '35.231.184.91', 
#        'PORT': 5432,
#    }
# }

# the real database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'battlecode',
        'USER': 'battlecode',
        'PASSWORD': '1f8e8ea0b0e34e279a6e71225da3419f1a4aef62',
        'HOST': '35.185.34.101',
        'PORT': 5432,
    }
}

GOOGLE_APPLICATION_CREDENTIALS = r"""{
  "type": "service_account",
  "project_id": "battlecode18",
  "private_key_id": "f32d9f2aaaca259491f2593611df3362d5754042",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC8oTlD1Du2xSKU\nDWg2pA+jA4KGquz/QD5xaVPATPd1j2xCnOADLdd/+GfL6AXa73KgkWi8HnFlScGT\njKUN2jvkjVsXUZvGBCRCcuQROseoTsupKfLogFtaIrD0VkyelmC8f7pp+QFSQO1M\namIi9KF8r95eKpGx/ktuzJICCg09DrwwgbgldBIEk95Bm+i/w2hgXm9sGqiKJFcn\nuKlye4guTv67VXx+iLRRwtlxQ1Y9FePpBDa2B/OF241YzVIgX4IChQegZAT8A3Ct\nunRphbP0VfrZrWWfJiCtjjm6DSCF1jRM1Nx1h97VmAd5JF6ZsEW6OAtVss1v/tcR\nAsVmiNbhAgMBAAECggEACGoyU2rvP4XvlxZ6hs5+lpV4YBDVugTYDEfoOTDNzMgp\nSpb0PNwRjCdNHRj0kunh7ZUTDKpYgW3fBXmtns60o4tlTAbjWbvzUKYOs9CRGdpr\nBjjFefcI7D5WMc48RIpdlicmDiZyN0THeURZLKlIX3c6hq2kOoInRBH69P2VDdtL\nzFSW/KTV19jzxqpdltbuBJ2ER37kM4/avUJX5PFnUZYP2Ja7xOuQ97xEJGotXU7r\nnqpyfMyFUdWj32vbiYIrynvhrbVq/Lv02TIRxVMVbG4DpMV/fN3QlqXMKlauEH1B\nk9UqneYKsNVPCeqRvqG5VsVzR56+oiQ/jpbhaHHWeQKBgQD4I52QfM22p9PLsGhc\nmaGfGVqCYmK2fZsA7qdGA94D37YT2kARSc+eKe9kNOaG5L4olGaGJdFJ3FsOvEFV\n/0EswSt8Y7hcBGqR2pkHsEno49AeA5lOed1e1Qf0KXptArm498FvSmmSx0moLDqm\n2ni1KiWAgn3mwrJJ9TbUJMb5eQKBgQDCmv4+Hri5aQyA+SXHIFF/lu9bo6kQg40K\n8/aBFGv0lcCZptvLDTPyU7fXulCuEpXMSckCP6IldJLrVj8sni7uyFhbx/ldlZvR\ng0qraqt9htjjK6L1dPYlWltcTuHBvLih+8BuuliHf/kpyn10WZewZGWtrgBaMV1Y\nh9JKefvWqQKBgEzYestsWyjeALFsCGXlDjB/YZBPd9KcQ4yeXB9Kw07f0TuEs6Kn\nAS0yP3kBCQNtg5Z9nuKcg5wkKe7+Th2b10tM53K2TznwBDD3Sb0f00PUiXdCFhA/\nnVbpEnWDAu8PkQS/daBJozhZj24NhHx33Dn+u254+xSj5yMQVdKNMTHBAoGAfUv1\n7mExZo9wcYn4/OCeGJxBuKsDK5LHuQmi6TEQ4QWaYFPCqFXz4E5uzAM19x4YPNQ1\nC7GU4LDR95wsSLoAVdXArjdvIwY0sQzrgrrHd6be9kUeQxPvd9VZhXF0gZzU89Z3\n69MnNPb8oh+x7rvQos3BebXSnD+0bk/k4fbwYyECgYEA7oAxW0Ty9ZQzSKTf748k\nHJ43aGs84f/j5WKToVKM7bAriYxKhe0/CyhUOXtzGk3h9VGO13leoIeLVxTv5tEK\nEor+OoWd/Y7zyC285Dy44wJjz/w070uW5qOEnvxbMxtpjHUoyfL1O1+Y1Fi+jE2A\nSMVNtj2ownCDDcsfO3qkowI=\n-----END PRIVATE KEY-----\n",
  "client_email": "bc20-compile-service@battlecode18.iam.gserviceaccount.com",
  "client_id": "116028038767616277407",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/bc20-compile-service%40battlecode18.iam.gserviceaccount.com"
}"""
